### ISSUE TITLE
Game Modes

### ISSUE THREAD

**Issue by Scott-Tatham** [Scott-Tatham/CardBored#19]
- [ ]  Capture The Flag.

- [ ]  Search And Destroy.

- [ ]  Payload.

- [ ]  Domination.

- [ ]  One Man Army (Sammy Boi's over powered 1 vs all mode).

- [ ]  UI menu implementation.
